export default {
  data: {
    projects: [
      {
        id: "1",
        name: "Stock photo",
        description: "",
        link: "https://sphoto.netlify.app/",
        image: "imagedata/sphoto-img.png",
        github: "https://github.com/muwaii/sphoto",
      },
      {
        id: "2",
        name: "Virtual keyboard",
        description: "",
        link: "https://simplevrkeyboard.netlify.app/",
        image: "imagedata/vrkeyboard-img.png",
        github: "https://github.com/muwaii/mb-vrkeyboard",
      },
      {
        id: "3",
        name: "Todo-list",
        description: "",
        link: "https://todudu.netlify.app/",
        image: "imagedata/todo-img.png",
        github: "https://github.com/muwaii/todolist",
      },
      {
        id: "4",
        name: "Meme generator",
        description: "",
        link: "https://catmemegen.netlify.app/",
        image: "imagedata/getmeme-img.png",
        github: "https://github.com/muwaii/memegen",
      },
      {
        id: "5",
        name: "URL Shorter",
        description: "",
        link: "https://shortermy.onrender.com",
        image: "imagedata/urlshorterner.jpeg",
        github: "https://github.com/muwaii/exam-1",
      },
      {
        id: "6",
        name: "GO get it",
        description: "",
        link: "https://sp-1.netlify.app/",
        image: "imagedata/plantoget.jpg",
        github: "https://github.com/muwaii/sp",
      },
      {
        id: "7",
        name: "My Store",
        description: "",
        link: "https://hommestore.netlify.app/",
        image: "imagedata/hommestore.jpg",
        github: "https://github.com/muwaii/store-mockup",
      },
    ],
  },
};
